Feature/player mission 01
youtakanke/mvc_learning_sapmle_shooting pull request #5
Opened 2020-08-04 16:35 UTC by peg0129

質問の為プッシュ致します。

2020-08-05 09:44 UTC, peg0129 commented
斜め移動の実装まで完了したのでレビューお願い致します。

2020-08-05 10:33 UTC, youtakanke requested changes
コメントいたしました！

2020-08-05 10:33 UTC, youtakanke commented on src/js/View/Player.js
> +        super (); //親constructor → MainManager.js
MainManagerは親ではなく、呼び出し元になります。
親クラスは継承元を意味します。そのためUnitBaseクラスのconstructorを初期化してます。

2020-08-05 10:33 UTC, youtakanke commented on src/js/View/Player.js
> +let downFlag = 0;
オブジェクト指向におけるグローバル変数はご法度になりますため、これらをクラスメンバにしてください。
また、flagなので数値でなくbooleanでお願いします。

2020-08-05 10:33 UTC, youtakanke commented on src/js/View/Player.js
> +        this.y = this.y + (upFlag - downFlag) * 4 / diagonal;
加算なので += にしましょう
```
this.x += (rightFlag - leftFlag) * 4 / diagonal; //5は移動スピード
this.y += (upFlag - downFlag) * 4 / diagonal;
```

2020-08-05 10:33 UTC, youtakanke commented on src/js/View/Player.js
> +},false);
フラグ同様、グローバル領域に定義することになってしまうため、
constructor内に定義お願いします。

2020-08-05 10:33 UTC, youtakanke commented on src/js/View/Player.js
> +        let yFlag = 0;
booleanにしましょう

2020-08-05 10:33 UTC, youtakanke commented on src/js/View/Player.js
> +        }
斜めにも等速になるようにやっていただいたのですね！
ありがとうございます。

2020-08-06 15:24 UTC, peg0129 commented
修正致しました。チェックお願い致します。

2020-08-07 07:24 UTC, peg0129 commented
addeventlistener部分の修正を致しました。チェックお願い致します。

2020-08-09 16:27 UTC, peg0129 commented
spaceキーでbullet発射実装致しました。チェックお願い致します。

2020-08-10 13:38 UTC, youtakanke requested changes
コメントいたしました〜

2020-08-10 13:38 UTC, youtakanke commented on src/js/View/Player.js
> +        window.addEventListener('keydown',(e) => {
window.addEventListener('keydown'
は35行目にも定義されていますので分けるのは冗長になってしまいますので統一しましょう

2020-08-10 13:38 UTC, youtakanke commented on src/js/View/Player.js
> +            bullet.setSpeed(4);
生成方法は newBulletで正解です。
次に、長押しで0.3秒ぐらいで規則的に発射させていただきたく、
改修をお願いいたします。

2020-08-11 17:05 UTC, peg0129 commented
質問の為一度プッシュ致しました。一度目を通して頂けると幸いです。よろしくお願い致します。

2020-08-16 07:54 UTC, closed without merging